INSERT INTO PAIS(id_pais, NOME) VALUES(1,'Brasil');
INSERT INTO ESTADO(ID_ESTADO, NOME, UF, ID_PAIS) VALUES(9,'Goiás','GO',1);
INSERT INTO CIDADE(ID_CIDADE, NOME, ID_ESTADO) VALUES(2007,'ANAPOLIS',9);